### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by rajandeepsingh13** [Prabhav2B/InverseKinematicExp#3]
I have an issue with this

**Comment by Prabhav2B** [comment]
And?

**Comment by rajandeepsingh13** [comment]
[](https://media.giphy.com/media/l3q2zVr6cu95nF6O4/giphy.gif)

**Comment by rajandeepsingh13** [comment]
https://media.giphy.com/media/l3q2zVr6cu95nF6O4/giphy.gif

**Comment by Prabhav2B** [comment]
uh huh
